name: bitcoin-price-pipelines

on:

  workflow_dispatch:
  
  schedule:
   - cron: '0 6 * * 3'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: execute python workflows from bash script
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_FS_API_KEY }}
        run: ./scripts/run_pipelines.sh

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        run: |
          git add prediction_dataframes/*.csv
          git commit -m "Update prediction dataframes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
